[package]
name = "geosym_wasm"
version = "0.1.0"
authors = ["ladronsuelto"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
rustfft = "6.1.0"
realfft = "3.2.0"
wasm-bindgen = "0.2"
